# Generated by Django 3.2.21 on 2023-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_expired',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_joined',
            field=models.TextField(default=0),
        ),
    ]
